name: Deploy to GitHub
os: linux
dist: bionic
addons:
  apt:
    packages:
      - python
      - python3
      - zip
script:
  - sh travis_scripts/deploy_master.sh
  - sh travis_scripts/deploy_xashbox-rus.sh
after_script:
      # Set up git user name and tag this commit
      - git config --local user.name "$GIT_NAME"
      - git config --local user.email "$GIT_EMAIL"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
      - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - export UPLOADTOOL_SUFFIX=$TRAVIS_TAG
      - bash upload.sh xashbox.pak xashbox.zip xashbox-rus.pak xashbox-rus.zip

