# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the github-workflow-test branch
  push:
    branches: [ github-workflow-test ]
  pull_request:
    branches: [ github-workflow-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install python python3 zip

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -a
          cd ..
          ls -a
          echo Checking home...
          ls $HOME
          echo Checking misc...
          ls /
          set
          sh travis_scripts/deploy_master.sh
          sh travis_scripts/deploy_xashbox-rus.sh
          export TRAVIS_TAG=${TRAVIS_TAG:-$(git log --format=%h -1)} 
          git tag $TRAVIS_TAG
          wget -c https://github.com/Vladislav4KZ/uploadtool/raw/master/upload.sh
          export UPLOADTOOL_SUFFIX=$TRAVIS_TAG
          bash upload.sh xashbox.pak xashbox.zip xashbox-rus.pak xashbox-rus.zip
